server:
  port: 8081
  servlet:
    context-path: /session-service/v1

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: session

agenda:
  service:
    name: 'agenda-service'
    url: 'http://localhost:8080/agenda-service/v1'